package util

import "errors"

func CatchPanicReturnError(fun func(), catchErrors ...error) error {
	var err error
	defer func() {
		r := recover()
		if r == nil {
			return
		}
		if err1, ok := r.(error); ok {
			for _, targetError := range catchErrors {
				if errors.Is(err1, targetError) {
					err = targetError
					return
				}
			}
		}
		panic(r)
	}()
	fun()
	return err
}
